Bug/Feature issue templates
CommunityToolkit/Maui.Markup pull request #147
Opened 2022-11-14 11:52 UTC by VladislavAntonyuk

### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

2022-11-15 16:45 UTC, michael-hawker commented
I'd suggest asking questions at the end if this is something the submitter wants to help with or not. We've found this useful in the WCT repo (feel free to take a look at our templates there).

2022-11-17 22:42 UTC, brminnick requested changes
Thanks Vlad! Just a few tweaks to focus on C# Markup and remove XAML

2022-11-17 22:42 UTC, brminnick commented on .github/ISSUE_TEMPLATE/bug_report_template.yml
> +        - **.NET MAUI CommunityToolkit**: 1.2.0
```suggestion
        - **.NET MAUI C# Markup CommunityToolkit**: 1.2.0

```

2022-11-17 22:42 UTC, brminnick commented on .github/ISSUE_TEMPLATE/bug_report_template.yml
> +        - .NET MAUI CommunityToolkit:
```suggestion
        - .NET MAUI C# Markup CommunityToolkit:
```

2022-11-17 22:42 UTC, brminnick commented on .github/ISSUE_TEMPLATE/open-a-new-feature-proposal.yml
> +    description: Please provide an example of how an end-user will use this feature. If this is a UI control, please an example of the feature being consumed in both a C# UIand a XAML UI.
```suggestion
    description: Please provide an example of how an end-user will use this feature. If this is a UI control, please an example of the feature being consumed in a C# UI.

```

2022-11-22 19:14 UTC, brminnick approved these changes

2022-11-22 19:35 UTC, merged