Replace BaseTheme with AppStyles
CommunityToolkit/Maui.Markup pull request #167
Opened 2022-12-27 11:02 UTC by HobDev

### Description of Change ###

 
As AppThemeBinding is available now I removed the old way of supporting Themes. Instead I use AddAppThemeBinding in the Styles.
 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

2023-01-05 18:35 UTC, brminnick commented
Thanks @HobDev! I really like this approach! 

Could you also [submit a PR to our docs](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/markup/extensions/style.md), adding this?  I think a lot of developers would find this really helpful too! 

It doesn't look like we have any documentation on theming, so I can see two ways you could approach this problem:
- Create a new doc page, something like `/docs/maui/markup/theming.md`
  - I think this would be best to help devs specifically looking for Light Theme / Dark Theme help
- Add to the existing `styles.md` doc `docs/maui/markup/extensions/style.md`
  - Add a `## Theming` section here
  - Putting it in the existing `Style` API docs may bury the info and be tough for devs to find, though

Once you have a PR open for the docs, I'll merge this PR 🙌

2023-01-05 18:49 UTC, brminnick requested changes
Thanks again @HobDev! Just a few recommendations to keep the color constants (I would put them in AppStyles.cs)

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/Base/BaseContentPage.cs
> +		this.SetAppThemeColor(ContentPage.BackgroundColorProperty, Color.FromArgb("F6F6EF"), Color.FromArgb("1B1B1B"));
Let's keep a constant for `PageBackgroundColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
> +					.AppThemeBinding(Button.TextColorProperty, Colors.Black,Color.FromArgb("FFF2EA"))
Let's keep a constant for `PrimaryTextColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
> +					.AppThemeBinding(Button.BackgroundColorProperty, Color.FromArgb("FF6601"), Color.FromArgb("C3560E"))
Let's keep a constant for `NavigationBarBackgroundColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
> +					.AppThemeBinding(Label.TextColorProperty, Colors.Black,Color.FromArgb("FFF2EA"))
Let's keep a constant for `PrimaryTextColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
> +					.AppThemeBinding(Label.BackgroundColorProperty, Color.FromArgb("FF6601"), Color.FromArgb("C3560E"))
Let's keep a constant for `NavigationBarBackgroundColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
> +
Let's remove this new blank line
```suggestion
```

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
> +					.AppThemeBinding(Label.TextColorProperty, Colors.Black, Color.FromArgb("FFF2EA"))
Let's keep a constant for `PrimaryTextColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
> +					.AppThemeBinding(Label.TextColorProperty, Colors.Black, Color.FromArgb("FFF2EA"))
Let's keep a constant for `PrimaryTextColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/ViewModels/NewsDetailViewModel.cs
> +			PreferredToolbarColor = App.Current?.RequestedTheme == AppTheme.Dark ? Color.FromArgb("BA7E56"): Color.FromArgb("FFE6D5"),
Let's move this logic to `AppStyles.cs` and let's keep a constant for `BrowserNavigationBarTextColor` and `BrowserNavigationBarBackgroundColor`

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Views/News/StoryDataTemplate.cs
> +				.Font(size: 16).AppThemeBinding(Label.TextColorProperty, Colors.Black, Color.FromArgb("FFF2EA"))
Let's keep a constant for `PrimaryTextColor` since it is used multiple times

2023-01-05 18:49 UTC, brminnick commented on samples/CommunityToolkit.Maui.Markup.Sample/Views/News/StoryDataTemplate.cs
> +				.Font(size: 13).AppThemeBinding(Label.TextColorProperty, Color.FromArgb("828282"), Color.FromArgb("E9DDD5"))
Let's keep a constant for `SecondaryTextColor` since it is used multiple times

2023-01-08 07:19 UTC, HobDev commented
> I am happy to provide the docs for how to style an application given I should have done so with the previous PR.

@bijington Thank you for the help. So I need not work on the docs as you are going to write it.

2023-01-08 17:20 UTC, HobDev commented
@brminnick  Thank you for the review. I made all colors `static readonly` in the latest commit. The Colors which are used in Dark Mode have Dark at the end of their name. I am not sure whether this naming is correct. Please let me know if further improvements are required.

2023-01-13 20:25 UTC, bijington commented
> Thanks @HobDev! I really like this approach!
> 
> Could you also [submit a PR to our docs](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/markup/extensions/style.md), adding this? I think a lot of developers would find this really helpful too!
> 
> It doesn't look like we have any documentation on theming, so I can see two ways you could approach this problem:
> 
> * Create a new doc page, something like `/docs/maui/markup/theming.md`
>   
>   * I think this would be best to help devs specifically looking for Light Theme / Dark Theme help
> * Add to the existing `styles.md` doc `docs/maui/markup/extensions/style.md`
>   
>   * Add a `## Theming` section here
>   * Putting it in the existing `Style` API docs may bury the info and be tough for devs to find, though
> 
> Once you have a PR open for the docs, I'll merge this PR 🙌
> 
> (I've added the [ pending documentation](https://github.com/CommunityToolkit/Maui.Markup/labels/pending%20documentation) This feature requires documentation and [ do not merge](https://github.com/CommunityToolkit/Maui.Markup/labels/do%20not%20merge) Do not merge this PR labels to remind me not to accidentally merge this until the docs are done)

I have added a PR at https://github.com/MicrosoftDocs/CommunityToolkit/pull/189 strangely I can't seem to assign you as a reviewer @brminnick

2023-01-18 18:39 UTC, brminnick approved these changes
Thanks @HobDev!!

And thank you @bijington for folding this [into the docs](https://github.com/MicrosoftDocs/CommunityToolkit/pull/189)! It'll be super helpful for devs in the future 💯

2023-01-18 18:51 UTC, merged